MVCStokTakip/Controllers/GirisYapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCStokTakip.Models.Entity;
using System.Web.Security;

namespace MVCStokTakip.Controllers
{
    public class GirisYapController : Controller
    {
        // GET: GirisYap
        DbMvcStokEntities db = new DbMvcStokEntities();

        public ActionResult Giris()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Giris(tblAdmin t)
        {
            var bilgiler = db.tblAdmin.FirstOrDefault(x => x.kullanici == t.kullanici && x.sifre == t.sifre);
            if(bilgiler != null)
            {
                FormsAuthentication.SetAuthCookie(bilgiler.kullanici, false);
                return RedirectToAction("Index", "Musteri");
            }
            else
            {
                
                return View();
            }
            return View();
        }
        public ActionResult CikisYap()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Giris");
        }
    }
}

MVCStokTakip/Views/GirisYap/Giris.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<!doctype html>
<html lang="tr">
<head>
    <title>Admin Giriş Paneli</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="~/login-form-12/css/style.css">

</head>
<body>
    <section class="ftco-section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6 text-center mb-5">
                    <h2 class="heading-section">Admin Giriş Paneli</h2>
                </div>
            </div>
            @using (Html.BeginForm("Giris", "GirisYap", FormMethod.Post))
            {
                <div class="row justify-content-center">
                    <div class="col-md-6 col-lg-4">
                        <div class="login-wrap p-0">
                            <h3 class="mb-4 text-center">Giris Yap</h3>
                            <form action="#" class="signin-form">
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="Kullanici Adi" required="required" name="kullanici">
                                </div>
                                <div class="form-group">
                                    <input type="password" class="form-control" placeholder="Sifre" required="required" name="sifre">
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="form-control btn btn-primary rounded submit px-3">Giris Yap</button>
                                </div>

                                <div class="form-group d-md-flex">
                                    <div class="w-50">
                                        <label class="checkbox-wrap checkbox-primary">
                                            Beni Hatırla
                                            <input type="checkbox" checked>
                                            <span class="checkmark"></span>
                                        </label>
                                    </div>

                                </div>
                            </form>


                        </div>
                    </div>
                </div>
            }
        </div>
    </section>


    <script src="~/login-form-12/js/jquery.min.js"></script>
    <script src="~/login-form-12/js/popper.js"></script>
    <script src="~/login-form-12/js/bootstrap.min.js"></script>
    <script src="~/login-form-12/js/main.js"></script>

</body>
</html>